
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// ASIHTTPRequest
#define COCOAPODS_POD_AVAILABLE_ASIHTTPRequest
#define COCOAPODS_VERSION_MAJOR_ASIHTTPRequest 1
#define COCOAPODS_VERSION_MINOR_ASIHTTPRequest 8
#define COCOAPODS_VERSION_PATCH_ASIHTTPRequest 2

// ASIHTTPRequest/ASIWebPageRequest
#define COCOAPODS_POD_AVAILABLE_ASIHTTPRequest_ASIWebPageRequest
#define COCOAPODS_VERSION_MAJOR_ASIHTTPRequest_ASIWebPageRequest 1
#define COCOAPODS_VERSION_MINOR_ASIHTTPRequest_ASIWebPageRequest 8
#define COCOAPODS_VERSION_PATCH_ASIHTTPRequest_ASIWebPageRequest 2

// ASIHTTPRequest/CloudFiles
#define COCOAPODS_POD_AVAILABLE_ASIHTTPRequest_CloudFiles
#define COCOAPODS_VERSION_MAJOR_ASIHTTPRequest_CloudFiles 1
#define COCOAPODS_VERSION_MINOR_ASIHTTPRequest_CloudFiles 8
#define COCOAPODS_VERSION_PATCH_ASIHTTPRequest_CloudFiles 2

// ASIHTTPRequest/Core
#define COCOAPODS_POD_AVAILABLE_ASIHTTPRequest_Core
#define COCOAPODS_VERSION_MAJOR_ASIHTTPRequest_Core 1
#define COCOAPODS_VERSION_MINOR_ASIHTTPRequest_Core 8
#define COCOAPODS_VERSION_PATCH_ASIHTTPRequest_Core 2

// ASIHTTPRequest/S3
#define COCOAPODS_POD_AVAILABLE_ASIHTTPRequest_S3
#define COCOAPODS_VERSION_MAJOR_ASIHTTPRequest_S3 1
#define COCOAPODS_VERSION_MINOR_ASIHTTPRequest_S3 8
#define COCOAPODS_VERSION_PATCH_ASIHTTPRequest_S3 2

// BeeFramework
#define COCOAPODS_POD_AVAILABLE_BeeFramework
#define COCOAPODS_VERSION_MAJOR_BeeFramework 0
#define COCOAPODS_VERSION_MINOR_BeeFramework 5
#define COCOAPODS_VERSION_PATCH_BeeFramework 2

// BeeFramework/Core
#define COCOAPODS_POD_AVAILABLE_BeeFramework_Core
#define COCOAPODS_VERSION_MAJOR_BeeFramework_Core 0
#define COCOAPODS_VERSION_MINOR_BeeFramework_Core 5
#define COCOAPODS_VERSION_PATCH_BeeFramework_Core 2

// BeeFramework/JSONKit
#define COCOAPODS_POD_AVAILABLE_BeeFramework_JSONKit
#define COCOAPODS_VERSION_MAJOR_BeeFramework_JSONKit 0
#define COCOAPODS_VERSION_MINOR_BeeFramework_JSONKit 5
#define COCOAPODS_VERSION_PATCH_BeeFramework_JSONKit 2

// CocoaAsyncSocket
#define COCOAPODS_POD_AVAILABLE_CocoaAsyncSocket
#define COCOAPODS_VERSION_MAJOR_CocoaAsyncSocket 7
#define COCOAPODS_VERSION_MINOR_CocoaAsyncSocket 3
#define COCOAPODS_VERSION_PATCH_CocoaAsyncSocket 5

// FMDB
#define COCOAPODS_POD_AVAILABLE_FMDB
#define COCOAPODS_VERSION_MAJOR_FMDB 2
#define COCOAPODS_VERSION_MINOR_FMDB 4
#define COCOAPODS_VERSION_PATCH_FMDB 0

// FMDB/common
#define COCOAPODS_POD_AVAILABLE_FMDB_common
#define COCOAPODS_VERSION_MAJOR_FMDB_common 2
#define COCOAPODS_VERSION_MINOR_FMDB_common 4
#define COCOAPODS_VERSION_PATCH_FMDB_common 0

// FMDB/standard
#define COCOAPODS_POD_AVAILABLE_FMDB_standard
#define COCOAPODS_VERSION_MAJOR_FMDB_standard 2
#define COCOAPODS_VERSION_MINOR_FMDB_standard 4
#define COCOAPODS_VERSION_PATCH_FMDB_standard 0

// OpenUDID
#define COCOAPODS_POD_AVAILABLE_OpenUDID
#define COCOAPODS_VERSION_MAJOR_OpenUDID 1
#define COCOAPODS_VERSION_MINOR_OpenUDID 0
#define COCOAPODS_VERSION_PATCH_OpenUDID 0

// Reachability
#define COCOAPODS_POD_AVAILABLE_Reachability
#define COCOAPODS_VERSION_MAJOR_Reachability 3
#define COCOAPODS_VERSION_MINOR_Reachability 2
#define COCOAPODS_VERSION_PATCH_Reachability 0

// TouchXML
#define COCOAPODS_POD_AVAILABLE_TouchXML
#define COCOAPODS_VERSION_MAJOR_TouchXML 0
#define COCOAPODS_VERSION_MINOR_TouchXML 1
#define COCOAPODS_VERSION_PATCH_TouchXML 0

// ZipArchive
#define COCOAPODS_POD_AVAILABLE_ZipArchive
#define COCOAPODS_VERSION_MAJOR_ZipArchive 1
#define COCOAPODS_VERSION_MINOR_ZipArchive 3
#define COCOAPODS_VERSION_PATCH_ZipArchive 0

